# Generated by Django 5.2.4 on 2025-07-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=64)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('picture', models.FileField(upload_to='')),
                ('is_available', models.BooleanField()),
                ('customers', models.ManyToManyField(related_name='products', to='main.customer')),
                ('tags', models.ManyToManyField(related_name='products', to='main.tag')),
            ],
        ),
    ]
