# Generated by Django 5.2.4 on 2025-07-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workers',
            field=models.ManyToManyField(related_name='projects', to='main.worker'),
        ),
    ]
