# Generated by Django 5.2.4 on 2025-07-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
    ]
